version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=laravel
      - MARIADB_DATABASE=laravel
      - MARIADB_PASSWORD=laravel
    ports:
      - 3006:3306
  laravel:
    tty: true
    image: docker.io/runthis/laravel:latest
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=laravel
      - DB_DATABASE=laravel
      - DB_PASSWORD=laravel
    depends_on:
      - mariadb
    ports:
      - 3005:3005
    volumes:
      - ./:/app
    command: bash ./bin/container-init.sh
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3010:80
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PMADB=phpmyadmin
    # privileged: true # Privileged mode could be required to run this container under Windows
